version: 2.1
    ############
    # Workflows
    ############

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
    ########
    # JOBS
    #######
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          DATABASE_URL: postgresql://postgres@localhost/mediminderx_test?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: mediminderx_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps2-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
      - run:
          command: |
            . venv/bin/activate
            python manage.py db upgrade
      - run:
          name: Run tests
          command: |
            pytest
